# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kWAuZ5nLrk9dtvMRbSRo1V775nvLeltR
"""

class school:
  countt=0
  def __init__(self,class_name,number_of_student):
    self.class_name=class_name
    self.number_of_student=number_of_student
    self.age=[]
    self.height=[]
    self.weight=[]

  def set_information(self):
    for i in range(self.number_of_student):
      age,height,weight=map(float,input().split())
      self.age.append(age)
      self.weight.append(weight)
      self.height.append(height)

  def ave_calculation(self):
    ave_height= sum(self.age)/self.number_of_student
    ave_weight= sum(self.weight)/self.number_of_student
    ave_age= sum(self.age)/self.number_of_student
    return ave_height,ave_age,ave_weight

num_student_A=int(input())
school_A= school("A",num_student_A)
school_A.set_information()


num_student_B= int(input())
school_B = school("B",num_student_B)
school_B.set_information()


ave_height_A,ave_weight_A, ave_age_A= school_A.ave_calculation()
ave_height_B,ave_weight_B, ave_age_B= school_B.ave_calculation()
print(f"{ave_height_A: .1f}")
print(f"{ave_weight_A: .1f}")
print(f"{ave_age_A: .1f}")
print(f"{ave_height_B: .1f}")
print(f"{ave_weight_B: .1f}")
print(f"{ave_age_B: .1f}")

if ave_height_A>ave_height_B:
  print(" class A  height average is better")
else:
  print("class B height average is better")







